### ISSUE TITLE
git-modified panel not found

### ISSUE THREAD

**Issue by faceair** [rjaviervega/tree-view-git-modified#6]
After upgrade to 1.1.0 , the git-modified panel not found. In the developer tools, I found this message

    Uncaught (in promise) TypeError: atom.packages.activatePackage(...).then(...).fail is not a function
        at /Users/faceair/.atom/packages/tree-view-git-modified/node_modules/atom-utils/lib/atom-utils.js:28:14
        at Array.forEach (native)
        at /Users/faceair/.atom/packages/tree-view-git-modified/node_modules/atom-utils/lib/atom-utils.js:24:25
        at module.exports.requirePackages (/Users/faceair/.atom/packages/tree-view-git-modified/node_modules/atom-utils/lib/atom-utils.js:8:14)
        at Object.module.exports.TreeViewGitModified.activate (/Users/faceair/.atom/packages/tree-view-git-modified/lib/tree-view-git-modified.coffee:27:5)
        at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
        at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
        at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
        at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
        at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
        at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
        at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:29
        at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:300:16)
        at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:19)
        at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:46)
        at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:625:21)

**Comment by edyywang** [comment]
Me too. Already installed the plug-in and used to show the open file pane, but somehow it just hidden and never show. Not sure how to open it

**Comment by rjaviervega** [comment]
I have reproduced the issue and I will work on a fix shortly.

**Comment by rearadmiral** [comment]
Seeing this as well. Thanks for looking into it.

**Comment by rjaviervega** [comment]
This issue has been fixed. Please upgrade the package and restart Atom. If you still don't see the Git Modified Panel try the option to toggle on Packages -> Tree View Git Modified -> Toggle (Crtl + Opt + O).

**Comment by rearadmiral** [comment]
Woohoo thanks! It's working again. I really appreciate this plugin since it lets me indulge my OCD tab closing but I can reopen the ones I care about easily.
